"""phase 2-4 operational schema

Revision ID: 38efe1b4df2f
Revises: fe76d174b22e
Create Date: 2026-08-09 18:40:09.321261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38efe1b4df2f'
down_revision: Union[str, None] = 'fe76d174b22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_model_name'), 'model_runs', ['model_name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('iata_code', sa.String(length=8), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.create_table('travel_agency_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=False),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('security_endorsed', sa.Boolean(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('alert_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('trigger_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_site_id'), 'alerts', ['site_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_trigger_key'), 'alerts', ['trigger_key'], unique=False)
    op.create_table('booking_referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('passenger_reference', sa.String(length=24), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('airline', sa.String(length=80), nullable=False),
    sa.Column('flight_search', sa.JSON(), nullable=False),
    sa.Column('redirect_url', sa.String(length=500), nullable=False),
    sa.Column('commission_estimate', sa.Float(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['travel_agency_partners.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_referrals_clicked_at'), 'booking_referrals', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_booking_referrals_passenger_reference'), 'booking_referrals', ['passenger_reference'], unique=False)
    op.create_index(op.f('ix_booking_referrals_site_id'), 'booking_referrals', ['site_id'], unique=False)
    op.create_table('capacity_building_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('participant_category', sa.String(length=48), nullable=False),
    sa.Column('participants_count', sa.Integer(), nullable=False),
    sa.Column('module_area', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capacity_building_activities_activity_type'), 'capacity_building_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_capacity_building_activities_participant_category'), 'capacity_building_activities', ['participant_category'], unique=False)
    op.create_index(op.f('ix_capacity_building_activities_site_id'), 'capacity_building_activities', ['site_id'], unique=False)
    op.create_index(op.f('ix_capacity_building_activities_status'), 'capacity_building_activities', ['status'], unique=False)
    op.create_table('cargo_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awb_number', sa.String(length=24), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=8), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('storage_location', sa.String(length=80), nullable=True),
    sa.Column('delayed', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_shipments_awb_number'), 'cargo_shipments', ['awb_number'], unique=True)
    op.create_index(op.f('ix_cargo_shipments_registered_at'), 'cargo_shipments', ['registered_at'], unique=False)
    op.create_index(op.f('ix_cargo_shipments_site_id'), 'cargo_shipments', ['site_id'], unique=False)
    op.create_index(op.f('ix_cargo_shipments_status'), 'cargo_shipments', ['status'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_site_id'), 'departments', ['site_id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('facility_type', sa.String(length=48), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_facility_type'), 'facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_facilities_site_id'), 'facilities', ['site_id'], unique=False)
    op.create_index(op.f('ix_facilities_status'), 'facilities', ['status'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('flight_number', sa.String(length=16), nullable=False),
    sa.Column('airline', sa.String(length=80), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=8), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('gate', sa.String(length=16), nullable=True),
    sa.Column('terminal', sa.String(length=16), nullable=True),
    sa.Column('passenger_capacity', sa.Integer(), nullable=False),
    sa.Column('passengers_booked', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_index(op.f('ix_flights_origin'), 'flights', ['origin'], unique=False)
    op.create_index(op.f('ix_flights_scheduled_departure'), 'flights', ['scheduled_departure'], unique=False)
    op.create_index(op.f('ix_flights_site_id'), 'flights', ['site_id'], unique=False)
    op.create_index(op.f('ix_flights_status'), 'flights', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_number', sa.String(length=24), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('reported_by', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.String(length=120), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_logged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_category'), 'incidents', ['category'], unique=False)
    op.create_index(op.f('ix_incidents_incident_number'), 'incidents', ['incident_number'], unique=True)
    op.create_index(op.f('ix_incidents_reported_at'), 'incidents', ['reported_at'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_site_id'), 'incidents', ['site_id'], unique=False)
    op.create_index(op.f('ix_incidents_source'), 'incidents', ['source'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=24), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technician', sa.String(length=120), nullable=True),
    sa.Column('reported_by', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repeat_key', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_category'), 'maintenance_requests', ['category'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_priority'), 'maintenance_requests', ['priority'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_repeat_key'), 'maintenance_requests', ['repeat_key'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_reported_at'), 'maintenance_requests', ['reported_at'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_request_number'), 'maintenance_requests', ['request_number'], unique=True)
    op.create_index(op.f('ix_maintenance_requests_site_id'), 'maintenance_requests', ['site_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_source'), 'maintenance_requests', ['source'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_status'), 'maintenance_requests', ['status'], unique=False)
    op.create_table('queue_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('queue_type', sa.String(length=32), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('predicted_length', sa.Float(), nullable=False),
    sa.Column('congestion_level', sa.String(length=16), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_predictions_congestion_level'), 'queue_predictions', ['congestion_level'], unique=False)
    op.create_index(op.f('ix_queue_predictions_queue_type'), 'queue_predictions', ['queue_type'], unique=False)
    op.create_index(op.f('ix_queue_predictions_site_id'), 'queue_predictions', ['site_id'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('queue_type', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('current_length', sa.Integer(), nullable=False),
    sa.Column('avg_wait_minutes', sa.Float(), nullable=False),
    sa.Column('open_counters', sa.Integer(), nullable=False),
    sa.Column('processing_rate', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_queue_type'), 'queues', ['queue_type'], unique=False)
    op.create_index(op.f('ix_queues_recorded_at'), 'queues', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_queues_site_id'), 'queues', ['site_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_site_id'), 'vendors', ['site_id'], unique=False)
    op.create_table('baggage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('bag_id', sa.String(length=24), nullable=False),
    sa.Column('passenger_reference', sa.String(length=24), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_location', sa.String(length=80), nullable=True),
    sa.Column('expected_location', sa.String(length=80), nullable=True),
    sa.Column('exception_type', sa.String(length=40), nullable=True),
    sa.Column('transfer_time_minutes', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baggage_bag_id'), 'baggage', ['bag_id'], unique=True)
    op.create_index(op.f('ix_baggage_flight_id'), 'baggage', ['flight_id'], unique=False)
    op.create_index(op.f('ix_baggage_passenger_reference'), 'baggage', ['passenger_reference'], unique=False)
    op.create_index(op.f('ix_baggage_risk_score'), 'baggage', ['risk_score'], unique=False)
    op.create_index(op.f('ix_baggage_site_id'), 'baggage', ['site_id'], unique=False)
    op.create_index(op.f('ix_baggage_status'), 'baggage', ['status'], unique=False)
    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=False),
    sa.Column('spent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_lines_category'), 'budget_lines', ['category'], unique=False)
    op.create_index(op.f('ix_budget_lines_department_id'), 'budget_lines', ['department_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_fiscal_year'), 'budget_lines', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_budget_lines_site_id'), 'budget_lines', ['site_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_number', sa.String(length=24), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('passenger_reference', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('linked_incident_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_complaint_number'), 'complaints', ['complaint_number'], unique=True)
    op.create_index(op.f('ix_complaints_passenger_reference'), 'complaints', ['passenger_reference'], unique=False)
    op.create_index(op.f('ix_complaints_site_id'), 'complaints', ['site_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_submitted_at'), 'complaints', ['submitted_at'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('employment_status', sa.String(length=24), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('report_to_employee_id', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['report_to_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_employee_number'), 'employees', ['employee_number'], unique=True)
    op.create_index(op.f('ix_employees_employment_status'), 'employees', ['employment_status'], unique=False)
    op.create_index(op.f('ix_employees_site_id'), 'employees', ['site_id'], unique=False)
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('passenger_reference', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_flight_id'), 'passengers', ['flight_id'], unique=False)
    op.create_index(op.f('ix_passengers_passenger_reference'), 'passengers', ['passenger_reference'], unique=False)
    op.create_index(op.f('ix_passengers_site_id'), 'passengers', ['site_id'], unique=False)
    op.create_index(op.f('ix_passengers_status'), 'passengers', ['status'], unique=False)
    op.create_table('baggage_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baggage_id', sa.Integer(), nullable=False),
    sa.Column('scan_event', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baggage_id'], ['baggage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baggage_scans_baggage_id'), 'baggage_scans', ['baggage_id'], unique=False)
    op.create_index(op.f('ix_baggage_scans_scanned_at'), 'baggage_scans', ['scanned_at'], unique=False)
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_number', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_employee_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('estimated_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('budget_line_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['requested_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requisitions_category'), 'purchase_requisitions', ['category'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_department_id'), 'purchase_requisitions', ['department_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_requested_by_employee_id'), 'purchase_requisitions', ['requested_by_employee_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_requisition_number'), 'purchase_requisitions', ['requisition_number'], unique=True)
    op.create_index(op.f('ix_purchase_requisitions_site_id'), 'purchase_requisitions', ['site_id'], unique=False)
    op.create_index(op.f('ix_purchase_requisitions_status'), 'purchase_requisitions', ['status'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=160), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('certificate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_employee_id'), 'training_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_training_records_site_id'), 'training_records', ['site_id'], unique=False)
    op.create_index(op.f('ix_training_records_status'), 'training_records', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_site_id'), 'audit_logs', ['site_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['purchase_requisitions.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_requisition_id'), 'purchase_orders', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_site_id'), 'purchase_orders', ['site_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_number', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('budget_line_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('vendor', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_budget_line_id'), 'expenses', ['budget_line_id'], unique=False)
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_department_id'), 'expenses', ['department_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_date'), 'expenses', ['expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_expense_number'), 'expenses', ['expense_number'], unique=True)
    op.create_index(op.f('ix_expenses_site_id'), 'expenses', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_site_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_number'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_department_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_budget_line_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_site_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_requisition_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_site_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_records_status'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_site_id'), table_name='training_records')
    op.drop_index(op.f('ix_training_records_employee_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_purchase_requisitions_status'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_site_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_requisition_number'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_requested_by_employee_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_department_id'), table_name='purchase_requisitions')
    op.drop_index(op.f('ix_purchase_requisitions_category'), table_name='purchase_requisitions')
    op.drop_table('purchase_requisitions')
    op.drop_index(op.f('ix_baggage_scans_scanned_at'), table_name='baggage_scans')
    op.drop_index(op.f('ix_baggage_scans_baggage_id'), table_name='baggage_scans')
    op.drop_table('baggage_scans')
    op.drop_index(op.f('ix_passengers_status'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_site_id'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_passenger_reference'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_flight_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_employees_site_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_number'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_complaints_submitted_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_site_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_passenger_reference'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_complaint_number'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_budget_lines_site_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_fiscal_year'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_department_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_category'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_baggage_status'), table_name='baggage')
    op.drop_index(op.f('ix_baggage_site_id'), table_name='baggage')
    op.drop_index(op.f('ix_baggage_risk_score'), table_name='baggage')
    op.drop_index(op.f('ix_baggage_passenger_reference'), table_name='baggage')
    op.drop_index(op.f('ix_baggage_flight_id'), table_name='baggage')
    op.drop_index(op.f('ix_baggage_bag_id'), table_name='baggage')
    op.drop_table('baggage')
    op.drop_index(op.f('ix_vendors_site_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_queues_site_id'), table_name='queues')
    op.drop_index(op.f('ix_queues_recorded_at'), table_name='queues')
    op.drop_index(op.f('ix_queues_queue_type'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_queue_predictions_site_id'), table_name='queue_predictions')
    op.drop_index(op.f('ix_queue_predictions_queue_type'), table_name='queue_predictions')
    op.drop_index(op.f('ix_queue_predictions_congestion_level'), table_name='queue_predictions')
    op.drop_table('queue_predictions')
    op.drop_index(op.f('ix_maintenance_requests_status'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_source'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_site_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_request_number'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_reported_at'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_repeat_key'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_priority'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_category'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_site_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reported_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_number'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_flights_status'), table_name='flights')
    op.drop_index(op.f('ix_flights_site_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_scheduled_departure'), table_name='flights')
    op.drop_index(op.f('ix_flights_origin'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_facilities_status'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_site_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_type'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_departments_site_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_cargo_shipments_status'), table_name='cargo_shipments')
    op.drop_index(op.f('ix_cargo_shipments_site_id'), table_name='cargo_shipments')
    op.drop_index(op.f('ix_cargo_shipments_registered_at'), table_name='cargo_shipments')
    op.drop_index(op.f('ix_cargo_shipments_awb_number'), table_name='cargo_shipments')
    op.drop_table('cargo_shipments')
    op.drop_index(op.f('ix_capacity_building_activities_status'), table_name='capacity_building_activities')
    op.drop_index(op.f('ix_capacity_building_activities_site_id'), table_name='capacity_building_activities')
    op.drop_index(op.f('ix_capacity_building_activities_participant_category'), table_name='capacity_building_activities')
    op.drop_index(op.f('ix_capacity_building_activities_activity_type'), table_name='capacity_building_activities')
    op.drop_table('capacity_building_activities')
    op.drop_index(op.f('ix_booking_referrals_site_id'), table_name='booking_referrals')
    op.drop_index(op.f('ix_booking_referrals_passenger_reference'), table_name='booking_referrals')
    op.drop_index(op.f('ix_booking_referrals_clicked_at'), table_name='booking_referrals')
    op.drop_table('booking_referrals')
    op.drop_index(op.f('ix_alerts_trigger_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_site_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('travel_agency_partners')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_model_runs_model_name'), table_name='model_runs')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
