"""Phase 1 core ERP schema

Revision ID: fe76d174b22e
Revises: 
Create Date: 2026-08-09 18:04:28.250803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe76d174b22e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
